import { PUBLIC_PROTECTED_IP_BLOCKING_ENABLE } from "$env/static/public";

export const PROTECTED_IP_BLOCKING_ENABLE = PUBLIC_PROTECTED_IP_BLOCKING_ENABLE
  ? PUBLIC_PROTECTED_IP_BLOCKING_ENABLE === "true"
  : false;
