import {
  PUBLIC_GATE_SERVICE_CANISTER_ID,
  PUBLIC_HOST_ICP,
  PUBLIC_X_CLIENT_ID,
} from "$env/static/public";

export const GATE_SERVICE_CANISTER_ID = PUBLIC_GATE_SERVICE_CANISTER_ID;
export const HOST_ICP = PUBLIC_HOST_ICP;
export const X_CLIENT_ID = PUBLIC_X_CLIENT_ID;
