pub const INTENT_LABEL_LINK_CREATION_FEE: &str = "LINK_CREATION_FEE";
pub const INTENT_LABEL_SEND_TIP_ASSET: &str = "SEND_TIP_ASSET";
pub const INTENT_LABEL_SEND_AIRDROP_ASSET: &str = "SEND_AIRDROP_ASSET";
pub const INTENT_LABEL_SEND_TOKEN_BASKET_ASSET: &str = "SEND_TOKEN_BASKET_ASSET";
pub const INTENT_LABEL_RECEIVE_PAYMENT_ASSET: &str = "RECEIVE_PAYMENT_ASSET";

pub const CREATE_LINK_ACTION: &str = "CreateLink";
pub const USE_LINK_ACTION: &str = "Use";
pub const WITHDRAW_LINK_ACTION: &str = "Withdraw";
pub const CONTINUE_ACTION: &str = "Continue";
