/**
 * TypeScript Code Generator
 *
 * Generates TypeScript types from JSON schemas.
 * Handles ICP-specific types: Principal and Nat (bigint).
 */

// Type mapping from JSON Schema format to TypeScript
const TYPE_MAP: Record<string, string> = {
  string: "string",
  integer: "number",
  number: "number",
  boolean: "boolean",
  array: "Array",
  object: "object",
};

// Special ICP type formats
const ICP_TYPE_MAP: Record<string, string> = {
  "icp-principal": "Principal",
  "icp-nat": "bigint",
  "rust-u64": "bigint",
};

interface SchemaDefinition {
  type?: string;
  format?: string;
  enum?: string[];
  description?: string;
  properties?: Record<string, SchemaDefinition>;
  items?: SchemaDefinition;
  required?: string[];
  $ref?: string;
  minimum?: number;
  maximum?: number;
}

interface Schema {
  definitions?: Record<string, SchemaDefinition>;
}

/**
 * Convert a JSON Schema type to TypeScript type
 */
function convertType(
  def: SchemaDefinition,
  definitions: Record<string, SchemaDefinition>
): string {
  // Handle $ref references
  if (def.$ref) {
    const refName = def.$ref.split("/").pop();
    return refName || "unknown";
  }

  // Handle ICP-specific formats
  if (def.format && ICP_TYPE_MAP[def.format]) {
    return ICP_TYPE_MAP[def.format];
  }

  // Handle arrays
  if (def.type === "array" && def.items) {
    const itemType = convertType(def.items, definitions);
    return `${itemType}[]`;
  }

  // Handle basic types
  return TYPE_MAP[def.type || "string"] || "unknown";
}

/**
 * Generate TypeScript enum from schema definition
 */
function generateEnum(name: string, def: SchemaDefinition): string {
  if (!def.enum) return "";

  const lines: string[] = [];

  // Add description if available
  if (def.description) {
    lines.push("/**");
    lines.push(` * ${def.description}`);
    lines.push(" */");
  }

  // Generate const object with enum values
  lines.push(`export const ${name} = {`);
  for (const value of def.enum) {
    lines.push(`  ${value}: '${value}',`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push(`export type ${name} = typeof ${name}[keyof typeof ${name}];`);

  return lines.join("\n");
}

/**
 * Generate TypeScript interface from schema definition
 */
function generateInterface(
  name: string,
  def: SchemaDefinition,
  definitions: Record<string, SchemaDefinition>
): string {
  if (!def.properties) return "";

  const lines: string[] = [];

  // Add description if available
  if (def.description) {
    lines.push("/**");
    lines.push(` * ${def.description}`);
    lines.push(" */");
  }

  lines.push(`export interface ${name} {`);

  const required = def.required || [];

  for (const [propName, propDef] of Object.entries(def.properties)) {
    // Add property description
    if (propDef.description) {
      lines.push(`  /** ${propDef.description} */`);
    }

    const propType = convertType(propDef, definitions);
    const optional = required.includes(propName) ? "" : "?";
    lines.push(`  ${propName}${optional}: ${propType};`);
  }

  lines.push("}");

  return lines.join("\n");
}

export const generateTypeScript = {
  /**
   * Generate TypeScript types from JSON Schema
   */
  types(schema: Schema): string {
    const lines: string[] = [
      "// AUTO-GENERATED FILE - DO NOT EDIT",
      "// Generated by @cashier/shared code generator",
      "// Source: schemas/types.schema.json",
      "",
      "import { Principal } from '@icp-sdk/core/principal';",
      "",
      "// =============================================================================",
      "// Enums",
      "// =============================================================================",
      "",
    ];

    const definitions = schema.definitions || {};
    const enums: string[] = [];
    const interfaces: string[] = [];

    // Separate enums and interfaces
    for (const [name, def] of Object.entries(definitions)) {
      if (def.enum) {
        enums.push(generateEnum(name, def));
      } else if (def.type === "object") {
        interfaces.push(generateInterface(name, def, definitions));
      }
    }

    // Add enums first
    lines.push(...enums.map((e) => e + "\n"));

    lines.push(
      "// ============================================================================="
    );
    lines.push("// Interfaces");
    lines.push(
      "// ============================================================================="
    );
    lines.push("");

    // Add interfaces
    lines.push(...interfaces.map((i) => i + "\n"));

    return lines.join("\n");
  },

  /**
   * Generate index file that exports all types and functions
   */
  index(
    includeTypes: boolean,
    includeFunctions: boolean,
    includeFeeTable: boolean = false
  ): string {
    const lines: string[] = [
      "// AUTO-GENERATED FILE - DO NOT EDIT",
      "// Generated by @cashier/shared code generator",
      "",
    ];

    if (includeTypes) {
      lines.push("export * from './types.js';");
    }

    if (includeFeeTable) {
      lines.push("export * from './fee-table.js';");
    }

    if (includeFunctions) {
      lines.push("export * from './functions.js';");
    }

    return lines.join("\n");
  },
};
