import {
  PUBLIC_SHARED_HOST_ICP,
  PUBLIC_SHARED_HOST_ICP_MAINNET,
  PUBLIC_TOKEN_ICPSWAP_INDEX_CANISTER_ID,
} from "$env/static/public";

// The ICPSwap index canister id
export const ICPSWAP_INDEX_CANISTER_ID = PUBLIC_TOKEN_ICPSWAP_INDEX_CANISTER_ID;

// The ICP mainnet host URL
export const ICP_MAINNET_HOST = PUBLIC_SHARED_HOST_ICP.includes("localhost")
  ? PUBLIC_SHARED_HOST_ICP_MAINNET
  : PUBLIC_SHARED_HOST_ICP;
