import {
  PUBLIC_BITCOIN_CKBTC_MINTER_CANISTER_ID,
  PUBLIC_BITCOIN_MEMPOOL_API_BASE_URL,
} from "$env/static/public";

export const MEMPOOL_API_BASE_URL = PUBLIC_BITCOIN_MEMPOOL_API_BASE_URL;
export const CKBTC_MINTER_CANISTER_ID = PUBLIC_BITCOIN_CKBTC_MINTER_CANISTER_ID;
