import {
  PUBLIC_BITCOIN_CKBTC_MINTER_CANISTER_ID,
  PUBLIC_BITCOIN_CKBTC_UPDATE_BALANCE_MAX_RETRY_TIMES,
  PUBLIC_BITCOIN_MEMPOOL_API_BASE_URLS,
  PUBLIC_BITCOIN_MEMPOOL_API_POOLING_INTERVAL_SECONDS,
} from "$env/static/public";

export const MEMPOOL_API_BASE_URLS: string[] = (
  PUBLIC_BITCOIN_MEMPOOL_API_BASE_URLS ?? ""
)
  .split(",")
  .map((url) => url.trim())
  .filter(Boolean);
export const MEMPOOL_API_POOLING_INTERVAL_SECONDS = Number(
  PUBLIC_BITCOIN_MEMPOOL_API_POOLING_INTERVAL_SECONDS,
);
export const CKBTC_MINTER_CANISTER_ID = PUBLIC_BITCOIN_CKBTC_MINTER_CANISTER_ID;
export const CKBTC_UPDATE_BALANCE_MAX_RETRY_TIMES = Number(
  PUBLIC_BITCOIN_CKBTC_UPDATE_BALANCE_MAX_RETRY_TIMES,
);

export const BRIDGE_PAGE_SIZE = 10;
