import { PUBLIC_FEATURE_FLAGS_ENABLE_LOCAL_IDENTITY_PROVIDER, PUBLIC_BACKEND_CANISTER_ID, PUBLIC_TOKEN_STORAGE_CANISTER_ID, PUBLIC_IC_INTERNET_IDENTITY_PROVIDER } from "$env/static/public";

export const FEATURE_FLAGS = {
    ENABLE_LOCAL_IDENTITY_PROVIDER: PUBLIC_FEATURE_FLAGS_ENABLE_LOCAL_IDENTITY_PROVIDER === "true",
}

export const TIMEOUT_NANO_SEC = 60 * 60 * 1_000_000_000// 1 hour;

export const TARGETS = [PUBLIC_BACKEND_CANISTER_ID, PUBLIC_TOKEN_STORAGE_CANISTER_ID];

export const IC_INTERNET_IDENTITY_PROVIDER = PUBLIC_IC_INTERNET_IDENTITY_PROVIDER || "https://id.ai";