name: Deploy all canisters to dev
on:
  pull_request:
      branches:
          - dev
      types:
          - closed

# Permissions needed for the GITHUB_TOKEN
permissions:
  actions: write # This allows the workflow to delete workflow runs
  contents: read # Default permission to read the repository contents

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node + pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-rust

      - name: Setup IC tooling
        uses: ./.github/actions/setup-ic-tools

      - name: Install Just command runner
        uses: extractions/setup-just@v4

      - name: Create Deployer private key file
        run: |
          echo "${{ secrets.DEPLOYER }}" > private_key.pem

      # DANGEROUS: This is a plaintext identity import
      - name: Import Deployer identity
        run: dfx identity import deployer private_key.pem --storage-mode=plaintext
      # DANGEROUS: Do not echo the private key to the console

      - name: Get cashier dev address
        run: |
          dfx identity use deployer
          dfx identity get-principal

      - name: Deploy to dev environment
        env:
            DFX_WARNING: -mainnet_plaintext_identity
        run: |
          owner=$(dfx identity get-principal)
          backend_log_filter="global,cashier=debug"
          token_storage_log_filter="global,cashier=debug,token_storage=debug"

          just build dev
          # pass log filters to just dfx_deploy so canisters pick the appropriate level
          just dfx_deploy "$owner" "--network=dev" "$backend_log_filter" "$token_storage_log_filter"