name: Deploy immutable canisters
on:
  push:
    branches:
      - feature/immut-contract
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: immut-contract

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: wasm32-unknown-unknown

      - name: Setup environment
        run: |
          export RUST_BACKTRACE="full" >> $GITHUB_ENV

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - name: Confirm successful installation
        run: dfx --version

      - name: Install ic-wasm
        run: |
          wget https://github.com/dfinity/ic-wasm/releases/download/0.9.8/ic-wasm-linux64 -O /usr/local/bin/ic-wasm
          chmod +x /usr/local/bin/ic-wasm

      - name: Install candid-extractor
        run: |
          wget https://github.com/dfinity/candid-extractor/releases/download/0.1.6/candid-extractor-x86_64-unknown-linux-gnu.tar.gz -O /tmp/candid-extractor-x86_64-unknown-linux-gnu.tar.gz
          tar -xvf /tmp/candid-extractor-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/candid-extractor

      - name: Install didc
        run: |
          wget https://github.com/dfinity/candid/releases/download/2025-10-16/didc-linux64 -O /usr/local/bin/didc
          chmod +x /usr/local/bin/didc

      - name: Install Just command runner
        uses: extractions/setup-just@v1

      - name: Export CI_user private key file
        run: |
          echo "${{ secrets.CI_USER_PEM }}" > private_key.pem

      # DANGEROUS: This is a plaintext identity import
      - name: Import CI_user identity
        run: dfx identity import ci_user private_key.pem --storage-mode=plaintext
      # DANGEROUS: Do not echo the private key to the console

      - name: Clean up private key file
        run: rm private_key.pem

      - name: Verify CI_user address
        run: |
          dfx identity use ci_user
          dfx identity get-principal

      - name: Cache dfx-orbit binary
        id: cache-dfx-orbit
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/dfx-orbit
          key: dfx-orbit-linux-control-panel-v0.4.0

      - name: Install dfx-orbit
        if: steps.cache-dfx-orbit.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/CashierHQ/orbit.git
          cd orbit
          cargo install -f --path tools/dfx-orbit/

      - name: Setup station
        run: |
          dfx-orbit station add cashier --station-id ${{ vars.ORBIT_STATION_ID }} --network ic

      - name: Verify station setup
        run: dfx-orbit station list

      - name: Verify CI_user is legitimate user of the station
        run: dfx-orbit me

      - name: Create the canister id
        env:
          DFX_WARNING: -mainnet_plaintext_identity
        run: |
          dfx canister create token_storage --ic

      - name: Verify the canister id
        run: dfx canister id token_storage --ic

      - name: Set Orbit station as the controller
        env:
          DFX_WARNING: -mainnet_plaintext_identity
        run: |
          dfx canister update-settings token_storage --set-controller ${{ vars.ORBIT_STATION_ID }} --ic

      - name: Set log filter
        id: log_filter
        run: |
          echo "filter=global,cashier=info,token_storage=info" >> $GITHUB_OUTPUT

      - name: Build canisters
        run: just build_canisters

      - name: Build candid hex args
        run: |
          owner=${{ vars.ORBIT_STATION_ID }}
          ckbtc_minter_id=${{ vars.CKBTC_MINTER_ID }}
          just build_token_storage_args_hex "$owner" "${{ steps.log_filter.outputs.filter }}" "$ckbtc_minter_id" token_storage_args
          echo "Token storage args:"
          cat token_storage_args.hex

      - name: Install canister using Orbit
        id: token_storage
        env:
          DFX_WARNING: -mainnet_plaintext_identity
        shell: bash
        run: |
          just orbit_upgrade token_storage "install" "ic" token_storage_args.hex
